import os

lines = [
    '<!DOCTYPE html>',
    '<html lang="zh-CN">',
    '<head>',
    '    <meta charset="UTF-8">',
    '    <meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '    <title>画图建议 + 图形库</title>',
    '    <style>',
    '        * { margin: 0; padding: 0; box-sizing: border-box; }',
    '        body { font-family: "Segoe UI", "Microsoft YaHei", "PingFang SC", sans-serif; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); min-height: 100vh; padding: 20px; }',
    '        .container { max-width: 1920px; margin: 0 auto; background: white; border-radius: 16px; box-shadow: 0 20px 60px rgba(0,0,0,0.3); padding: 30px; }',
    '        h1 { text-align: center; font-size: 32px; font-weight: 700; color: #2d3748; margin-bottom: 30px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; }',
    '        .main-content { display: flex; gap: 30px; min-height: 880px; }',
    '        .left-panel { flex: 0 0 500px; display: flex; flex-direction: column; gap: 20px; }',
    '        .right-panel { flex: 1; min-height: 880px; display: flex; flex-direction: column; }',
    '        .panel-title { font-size: 18px; font-weight: 600; color: #2d3748; margin-bottom: 16px; padding-bottom: 12px; border-bottom: 3px solid #667eea; display: flex; align-items: center; gap: 10px; }',
    '        .panel-title::before { content: ""; width: 6px; height: 24px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); border-radius: 3px; }',
    '        .form-section { background: linear-gradient(145deg, #f8f9fa 0%, #e9ecef 100%); border-radius: 12px; padding: 24px; box-shadow: 0 4px 12px rgba(0,0,0,0.08); }',
    '        .form-group { margin-bottom: 20px; }',
    '        label { display: block; font-weight: 600; color: #4a5568; margin-bottom: 8px; font-size: 14px; letter-spacing: 0.3px; }',
    '        input, textarea { width: 100%; padding: 12px 16px; border: 2px solid #e2e8f0; border-radius: 8px; font-size: 14px; font-family: inherit; transition: all 0.3s ease; background: white; }',
    '        input:focus, textarea:focus { outline: none; border-color: #667eea; box-shadow: 0 0 0 4px rgba(102, 126, 234, 0.1); }',
    '        textarea { resize: vertical; min-height: 100px; line-height: 1.6; }',
    '        .btn { padding: 12px 28px; font-size: 15px; font-weight: 600; cursor: pointer; border: none; border-radius: 8px; transition: all 0.3s ease; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }',
    '        .btn:hover { transform: translateY(-2px); box-shadow: 0 4px 12px rgba(0,0,0,0.15); }',
    '        .btn:active { transform: translateY(0); }',
    '        .btn-primary { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; }',
    '        .btn-primary:hover { background: linear-gradient(135deg, #5a67d8 0%, #6b46c1 100%); }',
    '        .btn-secondary { background: white; color: #4a5568; border: 2px solid #e2e8f0; }',
    '        .btn-secondary:hover { background: #f7fafc; border-color: #cbd5e0; }',
    '        .btn-group { display: flex; gap: 12px; }',
    '        .suggestions-output { background: linear-gradient(145deg, #ffffff 0%, #f8f9fa 100%); border-radius: 12px; padding: 24px; flex: 1; overflow-y: auto; max-height: 540px; box-shadow: 0 4px 12px rgba(0,0,0,0.08); border: 1px solid #e2e8f0; }',
    '        .suggestions-content { font-size: 15px; line-height: 1.9; color: #2d3748; }',
    '        .suggestions-content h1 { font-size: 24px; font-weight: 700; color: #2d3748; margin: 0 0 20px 0; padding-bottom: 14px; border-bottom: 3px solid #667eea; text-align: left; -webkit-text-fill-color: #2d3748; background: none; }',
    '        .suggestions-content h2 { font-size: 20px; font-weight: 600; color: #4a5568; margin: 24px 0 14px 0; padding: 12px 16px; background: linear-gradient(135deg, rgba(102, 126, 234, 0.1) 0%, rgba(118, 75, 162, 0.1) 100%); border-radius: 8px; border-left: 4px solid #667eea; }',
    '        .suggestions-content h3 { font-size: 17px; font-weight: 600; color: #4a5568; margin: 18px 0 12px 0; }',
    '        .suggestions-content p { margin: 10px 0; color: #4a5568; text-align: justify; }',
    '        .suggestions-content ul { margin: 14px 0 14px 28px; color: #4a5568; }',
    '        .suggestions-content ol { margin: 14px 0 14px 28px; color: #4a5568; }',
    '        .suggestions-content li { margin: 8px 0; line-height: 1.8; padding-left: 4px; }',
    '        .suggestions-content strong { color: #2d3748; font-weight: 600; }',
    '        .suggestions-content code { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 3px 8px; border-radius: 5px; font-family: "Consolas", "Monaco", monospace; font-size: 13px; font-weight: 500; }',
    '        .loading { text-align: center; color: #718096; padding: 40px; font-size: 15px; display: flex; flex-direction: column; align-items: center; gap: 16px; }',
    '        .loading::before { content: ""; width: 40px; height: 40px; border: 4px solid #e2e8f0; border-top-color: #667eea; border-radius: 50%; animation: spin 1s linear infinite; }',
    '        @keyframes spin { to { transform: rotate(360deg); } }',
    '        .error { color: #c53030; background: linear-gradient(135deg, #fff5f5 0%, #fed7d7 100%); padding: 20px; border-radius: 10px; border-left: 5px solid #fc8181; font-size: 14px; line-height: 1.8; box-shadow: 0 2px 8px rgba(197, 48, 48, 0.1); }',
    '        .error strong { color: #c53030; }',
    '        .ggb-frame { width: 100%; height: 100%; border: 2px solid #e2e8f0; border-radius: 12px; box-shadow: 0 4px 12px rgba(0,0,0,0.08); }',
    '        .placeholder-text { color: #718096; font-size: 15px; line-height: 1.9; text-align: center; padding: 40px 20px; }',
    '        .suggestions-output::-webkit-scrollbar { width: 8px; }',
    '        .suggestions-output::-webkit-scrollbar-track { background: #f1f1f1; border-radius: 4px; }',
    '        .suggestions-output::-webkit-scrollbar-thumb { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); border-radius: 4px; }',
    '        .suggestions-output::-webkit-scrollbar-thumb:hover { background: linear-gradient(135deg, #5a67d8 0%, #6b46c1 100%); }',
    '    </style>',
    '</head>',
    '<body>',
    '    <div class="container">',
    '        <h1>🎨 画图建议 + 图形库</h1>',
    '        <div class="main-content">',
    '            <div class="left-panel">',
    '                <div class="form-section">',
    '                    <div class="panel-title">📝 获取画图建议</div>',
    '                    <div class="form-group">',
    '                        <label for="chapter">章节</label>',
    '                        <input type="text" id="chapter" placeholder="例如：三角函数">',
    '                    </div>',
    '                    <div class="form-group">',
    '                        <label for="topic">主题</label>',
    '                        <input type="text" id="topic" placeholder="例如：正弦函数图像">',
    '                    </div>',
    '                    <div class="form-group">',
    '                        <label for="teaching_purpose">教学用途</label>',
    '                        <textarea id="teaching_purpose" placeholder="例如：帮助学生理解正弦函数的周期性和相位变化"></textarea>',
    '                    </div>',
    '                    <div class="btn-group">',
    '                        <button class="btn btn-primary" onclick="getSuggestions()">✨ 获取建议</button>',
    '                        <button class="btn btn-secondary" onclick="clearSuggestions()">🗑️ 清空</button>',
    '                    </div>',
    '                </div>',
    '                <div class="suggestions-output" id="suggestions-output">',
    '                    <div class="suggestions-content" id="suggestions-content">',
    '                        <div class="placeholder-text">👋 填写上方表单，点击"获取建议"按钮来获取画图建议。建议将显示在这里，您可以根据建议在右侧的图形库中画图。</div>',
    '                    </div>',
    '                </div>',
    '            </div>',
    '            <div class="right-panel">',
    '                <div class="panel-title">🎯 图形库</div>',
    '                <iframe class="ggb-frame" id="ggb-frame" src="/geometry-library"></iframe>',
    '            </div>',
    '        </div>',
    '    </div>',
    '',
    '    <script>',
    '        function simpleMarkdown(text) {',
    '            if (!text) return "";',
    '            ',
    '            let html = text',
    '                .replace(/&/g, "&amp;")',
    '                .replace(/</g, "&lt;")',
    '                .replace(/>/g, "&gt;");',
    '            ',
    '            html = html.replace(/^### (.*)$/gm, "<h3>$1</h3>");',
    '            html = html.replace(/^## (.*)$/gm, "<h2>$1</h2>");',
    '            html = html.replace(/^# (.*)$/gm, "<h1>$1</h1>");',
    '            ',
    '            html = html.replace(/\\*\\*(.*?)\\*\\*/g, "<strong>$1</strong>");',
    '            html = html.replace(/`([^`]+)`/g, "<code>$1</code>");',
    '            ',
    '            const lines = html.split("\\n");',
    '            let result = [];',
    '            let inList = false;',
    '            let listType = null;',
    '            ',
    '            for (let i = 0; i < lines.length; i++) {',
    '                let line = lines[i].trim();',
    '                ',
    '                if (!line) {',
    '                    if (inList) {',
    '                        result.push("</" + listType + ">");',
    '                        inList = false;',
    '                        listType = null;',
    '                    }',
    '                    continue;',
    '                }',
    '                ',
    '                if (line.match(/^<h[1-3]>/)) {',
    '                    if (inList) {',
    '                        result.push("</" + listType + ">");',
    '                        inList = false;',
    '                        listType = null;',
    '                    }',
    '                    result.push(line);',
    '                } else if (line.match(/^\\d+\\.\\s+/)) {',
    '                    if (!inList || listType !== "ol") {',
    '                        if (inList) {',
    '                            result.push("</" + listType + ">");',
    '                        }',
    '                        result.push("<ol>");',
    '                        inList = true;',
    '                        listType = "ol";',
    '                    }',
    '                    result.push("<li>" + line.replace(/^\\d+\\.\\s+/, "") + "</li>");',
    '                } else if (line.match(/^[-+]\\s+/)) {',
    '                    if (!inList || listType !== "ul") {',
    '                        if (inList) {',
    '                            result.push("</" + listType + ">");',
    '                        }',
    '                        result.push("<ul>");',
    '                        inList = true;',
    '                        listType = "ul";',
    '                    }',
    '                    result.push("<li>" + line.replace(/^[-+]\\s+/, "") + "</li>");',
    '                } else {',
    '                    if (inList) {',
    '                        result.push("</" + listType + ">");',
    '                        inList = false;',
    '                        listType = null;',
    '                    }',
    '                    result.push("<p>" + line + "</p>");',
    '                }',
    '            }',
    '            ',
    '            if (inList) {',
    '                result.push("</" + listType + ">");',
    '            }',
    '            ',
    '            return result.join("\\n");',
    '        }',
    '',
    '        async function getSuggestions() {',
    '            const chapter = document.getElementById("chapter").value.trim();',
    '            const topic = document.getElementById("topic").value.trim();',
    '            const teaching_purpose = document.getElementById("teaching_purpose").value.trim();',
    '            ',
    '            if (!chapter || !topic || !teaching_purpose) {',
    '                alert("请填写所有字段！");',
    '                return;',
    '            }',
    '            ',
    '            const outputDiv = document.getElementById("suggestions-content");',
    '            outputDiv.innerHTML = \'<div class="loading">正在获取画图建议...</div>\';',
    '            ',
    '            try {',
    '                const response = await fetch("/ggb/innovation-suggestions", {',
    '                    method: "POST",',
    '                    headers: { "Content-Type": "application/json" },',
    '                    body: JSON.stringify({',
    '                        chapter: chapter,',
    '                        topic: topic,',
    '                        teaching_purpose: teaching_purpose',
    '                    })',
    '                });',
    '                ',
    '                if (!response.ok) throw new Error("HTTP error! status: " + response.status);',
    '                ',
    '                const data = await response.json();',
    '                ',
    '                if (data.status === "success" && data.data) {',
    '                    let content = data.data.suggestions || "未能获取到详细建议，请稍后重试。";',
    '                    outputDiv.innerHTML = simpleMarkdown(content);',
    '                } else {',
    '                    throw new Error(data.error || "获取建议失败");',
    '                }',
    '            } catch (error) {',
    '                outputDiv.innerHTML = \'<div class="error">\' +',
    '                    "<strong>获取画图建议功能需要 FastAPI 后端</strong><br><br>" +',
    '                    "当前使用的是简单的 HTTP 服务器，不支持后端 API 调用。<br><br>" +',
    '                    "<strong>说明：</strong><br>" +',
    '                    "• 右侧的图形库功能可以正常使用<br>" +',
    '                    "• 要获取 AI 画图建议，需要启动 FastAPI 后端<br>" +',
    '                    "• 图形库可以独立使用，您可以根据需要自由画图！" +',
    '                "</div>";',
    '            }',
    '        }',
    '        ',
    '        function clearSuggestions() {',
    '            document.getElementById("chapter").value = "";',
    '            document.getElementById("topic").value = "";',
    '            document.getElementById("teaching_purpose").value = "";',
    '            document.getElementById("suggestions-content").innerHTML = \'<div class="placeholder-text">👋 填写上方表单，点击"获取建议"按钮来获取画图建议。建议将显示在这里，您可以根据建议在右侧的图形库中画图。</div>\';',
    '        }',
    '    </script>',
    '</body>',
    '</html>'
]

with open('geometry_with_suggestions.html', 'w', encoding='utf-8') as f:
    for line in lines:
        f.write(line + '\n')

print('✅ HTML 文件已成功创建！')
