"""
常量定义模块

职责：
- 定义项目中使用的常量
- 集中管理配置值

依赖：
- 无外部依赖
"""

# API相关常量
API_PREFIX = ""
API_TAGS = ["LangGraph API"]

# 助手相关常量
ASSISTANT_ID = "math-agent"
ASSISTANT_NAME = "高中数学资源智能体"
ASSISTANT_DESCRIPTION = "提供高中数学教案生成、资源检索、可视化设计建议等功能"
GRAPH_ID = "math-agent"
MODEL_NAME = "deepseek"
VERSION = "1.0.0"
CATEGORY = "education"

# 意图类型常量
INTENT_SEARCH = "search"
INTENT_GENERATE_LESSON_PLAN = "generate_lesson_plan"
INTENT_VISUALIZATION = "visualization"

# 资源类型常量
RESOURCE_TYPE_LESSON_PLAN = "lesson_plan"
RESOURCE_TYPE_SYLLABUS = "syllabus"
RESOURCE_TYPE_COURSEWARE = "courseware"
RESOURCE_TYPE_LESSON_CASE = "lesson_case"
RESOURCE_TYPE_GGB = "ggb"
RESOURCE_TYPE_VISUALIZATION = "visualization"
RESOURCE_TYPE_EXERCISE = "exercise"
RESOURCE_TYPE_THEORY = "theory"

# 资源类型映射（中文）
RESOURCE_TYPE_NAMES = {
    RESOURCE_TYPE_LESSON_PLAN: "教案资源",
    RESOURCE_TYPE_SYLLABUS: "教学大纲",
    RESOURCE_TYPE_COURSEWARE: "课件资源",
    RESOURCE_TYPE_LESSON_CASE: "课例资源",
    RESOURCE_TYPE_GGB: "GGB资源",
    RESOURCE_TYPE_VISUALIZATION: "可视化资源",
    RESOURCE_TYPE_EXERCISE: "习题资源",
    RESOURCE_TYPE_THEORY: "理论资源"
}

# 资源类型图标
RESOURCE_TYPE_ICONS = {
    RESOURCE_TYPE_LESSON_PLAN: "📚",
    RESOURCE_TYPE_SYLLABUS: "📋",
    RESOURCE_TYPE_COURSEWARE: "📊",
    RESOURCE_TYPE_LESSON_CASE: "🎬",
    RESOURCE_TYPE_GGB: "🔧",
    RESOURCE_TYPE_VISUALIZATION: "🎨",
    RESOURCE_TYPE_EXERCISE: "📝",
    RESOURCE_TYPE_THEORY: "💡"
}

# ChromaDB相关常量
COLLECTION_NAME = "knowledge_base"
DEFAULT_N_RESULTS = 20

# 模型相关常量
DEEPSEEK_MODEL = "deepseek-chat"
DEFAULT_TEMPERATURE = 0.3
DEFAULT_MAX_TOKENS = 2000
LESSON_PLAN_MAX_TOKENS = 4000

# 内容处理相关常量
DEFAULT_SUMMARY_LENGTH = 150
DEFAULT_CONTENT_LENGTH = 200

# 状态相关常量
STATUS_PENDING = "pending"
STATUS_RUNNING = "running"
STATUS_SUCCESS = "success"
STATUS_ERROR = "error"
STATUS_CANCELLED = "cancelled"

# 步骤相关常量
STEP_INTENT_UNDERSTANDING = "intent_understanding"
STEP_RESOURCE_RETRIEVAL = "resource_retrieval"
STEP_LESSON_PLAN_GENERATION = "lesson_plan_generation"
STEP_VISUALIZATION_SUGGESTIONS = "visualization_suggestions"
STEP_RESPONSE_FORMATTING = "response_formatting"

# 步骤名称映射
STEP_NAMES = {
    STEP_INTENT_UNDERSTANDING: "意图理解",
    STEP_RESOURCE_RETRIEVAL: "资源检索",
    STEP_LESSON_PLAN_GENERATION: "教案生成",
    STEP_VISUALIZATION_SUGGESTIONS: "可视化建议",
    STEP_RESPONSE_FORMATTING: "响应生成"
}

# 错误消息常量
ERROR_EMPTY_INPUT = "用户输入为空"
ERROR_MODEL_NOT_INITIALIZED = "模型未初始化，请检查配置"
ERROR_CHROMADB_NOT_FOUND = "ChromaDB数据库不存在"
ERROR_RESOURCE_RETRIEVAL_FAILED = "资源检索失败"
ERROR_LESSON_PLAN_GENERATION_FAILED = "教案生成失败"
ERROR_VISUALIZATION_ADVICE_FAILED = "可视化建议生成失败"
ERROR_RESPONSE_FORMATTING_FAILED = "响应格式化失败"

# 默认值常量
DEFAULT_CONFIDENCE = 0.9
DEFAULT_RELEVANCE_THRESHOLD = 0.5

# HTTP状态码常量
HTTP_STATUS_OK = 200
HTTP_STATUS_CREATED = 201
HTTP_STATUS_BAD_REQUEST = 400
HTTP_STATUS_NOT_FOUND = 404
HTTP_STATUS_INTERNAL_ERROR = 500

# 分页相关常量
DEFAULT_LIMIT = 10
DEFAULT_OFFSET = 0
MAX_LIMIT = 100

# 日志级别常量
LOG_LEVEL_DEBUG = "DEBUG"
LOG_LEVEL_INFO = "INFO"
LOG_LEVEL_WARNING = "WARNING"
LOG_LEVEL_ERROR = "ERROR"
LOG_LEVEL_CRITICAL = "CRITICAL"
